image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn install


build site:
  image: node:latest
  stage: build
  script:
    - yarn run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  
unit test:
  image: node:latest
  stage: test
  script:
    - yarn run test:unit

deploy production:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  script:
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete --parallel=10 dist/ $FTP_PATH; bye"
  only: 
    - production

pages: 
  image: node:latest
  stage: deploy
  script: 
    - yarn run build
    - mv public public-vue
    - mv dist public
  artifacts: 
    paths: 
      - public
  only: 
    - master